In [1]:
%load_ext autoreload
%autoreload 2

import sys
import os

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from ros_nodes.particle_filter import *
from ros_nodes.probability_funcs import *
import matplotlib.pyplot as plt

import time

import torch
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
import numpy as np
from PIL import Image as PILImage
import cv2


from utils import *
from models.CtRNet import CtRNet


/usr/local/lib/python3.8/dist-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
import argparse
parser = argparse.ArgumentParser()

args = parser.parse_args("")

args.base_dir = "/home/workspace/src/ctrnet-robot-pose-estimation-ros"
args.use_gpu = True
args.trained_on_multi_gpus = True
args.keypoint_seg_model_path = os.path.join(args.base_dir,"weights/panda/panda-3cam_azure/net.pth")
args.urdf_file = os.path.join(args.base_dir,"urdfs/Panda/panda.urdf")

args.robot_name = 'Panda' # "Panda" or "Baxter_left_arm"
args.n_kp = 7
args.height = 480
args.width = 640
args.fx, args.fy, args.px, args.py = 399.6578776041667, 399.4959309895833, 319.8955891927083, 244.0602823893229
args.scale = 0.5 # scale the input image size to (320,240)

# scale the camera parameters
args.width = int(args.width * args.scale)
args.height = int(args.height * args.scale)
args.fx = args.fx * args.scale
args.fy = args.fy * args.scale
args.px = args.px * args.scale
args.py = args.py * args.scale

In [3]:
trans_to_tensor = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

def preprocess_img(cv_img,args):
    image_pil = PILImage.fromarray(cv_img)
    width, height = image_pil.size
    new_size = (int(width*args.scale),int(height*args.scale))
    image_pil = image_pil.resize(new_size)
    image = trans_to_tensor(image_pil)
    return image

CtRNet = CtRNet(args)

/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=DeepLabV3_ResNet50_Weights.COCO_WITH_VOC_LABELS_V1`. You can also use `weights=DeepLabV3_ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Loading keypoint segmentation model from /home/workspace/src/ctrnet-robot-pose-estimation-ros/weights/panda/panda-3cam_azure/net.pth
Camera intrinsics: [[199.8289388    0.         159.9477946 ]
 [  0.         199.74796549 122.03014119]
 [  0.           0.           1.        ]]
Robot model: Panda


In [4]:
cv_img = cv2.imread(os.path.join(args.base_dir,"images/panda.jpg"))
cv_img = cv2.cvtColor(cv_img, cv2.COLOR_BGR2RGB)
image = preprocess_img(cv_img,args)
if args.use_gpu:
    image = image.cuda()

joint_angles = np.array([ 0.0200, -0.9641, -0.0662, -2.7979, -0.0469,  1.9289,  0.9137])

cTr, points_2d, segmentation, confidence = CtRNet.inference_single_image(image, joint_angles)
print(CtRNet.cTr_to_pose_matrix(cTr))

tensor([[[ 0.8578,  0.5140, -0.0044, -0.1976],
         [ 0.0951, -0.1672, -0.9813,  0.3963],
         [-0.5051,  0.8414, -0.1923,  1.0495],
         [ 0.0000,  0.0000,  0.0000,  1.0000]]], device='cuda:0',
       grad_fn=<CopySlices>)


In [39]:
init_std = np.array([
                        1.0e-2, 1.0e-2, 1.0e-2, # ori
                        1.0e-3, 1.0e-3, 1.0e-3, # pos
                    ])
pred_std = np.array([1.0e-4, 1.0e-4, 1.0e-4,
                     2.5e-5, 2.5e-5, 2.5e-5])
pf = ParticleFilter(num_states=6,
                    init_distribution=sample_gaussian,
                    motion_model=additive_gaussian,
                    obs_model=point_feature_obs,
                    num_particles=200)
pf.init_filter(init_std)

pf.predict(pred_std)

cam = None
gamma = 0.15
pf.update(points_2d, CtRNet, joint_angles, cam, cTr, gamma)
pf.get_mean_particle()

array([ 7.70867818e-04,  2.20735059e-04, -2.42856312e-04, -6.64493705e-05,
       -3.56074489e-05,  9.41605532e-05])